import { Shield, MessageSquare, Calculator, Zap, Link as LinkIcon } from "lucide-react";

// This data is derived directly from your README features!
export const splitmateTimelineData = [
  {
    id: 1,
    title: "Coinbase Auth",
    date: "Core",
    content: "Securely connect your identity and assets using your Coinbase Wallet. The foundation of trust on-chain.",
    category: "Security",
    icon: Shield,
    relatedIds: [2],
    status: "completed" as const,
    energy: 100,
  },
  {
    id: 2,
    title: "XMTP Messaging",
    date: "Integration",
    content: "Leverages the XMTP network to understand context within group chats, making expense sharing seamless.",
    category: "Communication",
    icon: MessageSquare,
    relatedIds: [1, 3],
    status: "completed" as const,
    energy: 95,
  },
  {
    id: 3,
    title: "Smart Splitting",
    date: "Logic",
    content: "Our smart contract engine automatically and fairly calculates who owes what, eliminating manual math.",
    category: "Utility",
    icon: Calculator,
    relatedIds: [2, 4],
    status: "completed" as const,
    energy: 90,
  },
  {
    id: 4,
    title: "Base Payments",
    date: "Execution",
    content: "Settle up instantly with friends using fast, low-cost crypto payments on the Base blockchain.",
    category: "Transaction",
    icon: Zap,
    relatedIds: [3, 5],
    status: "completed" as const,
    energy: 100,
  },
    {
    id: 5,
    title: "On-Chain Record",
    date: "Transparency",
    content: "Every split and payment is a transparent, immutable record on the blockchain for ultimate clarity.",
    category: "Trust",
    icon: LinkIcon,
    relatedIds: [4],
    status: "completed" as const,
    energy: 85,
  },
];