import "@coinbase/onchainkit/styles.css";
import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import { AmountProvider } from "./context/AmountContext";
import {XMTPProvider} from "./context/XMTPContext";
import BillNotificationListener from './service/BillNotificationListener';
export const metadata: Metadata = {
  title: process.env.NEXT_PUBLIC_ONCHAINKIT_PROJECT_NAME,
  description:
    "Generated by `create-onchain`, a Next.js template for OnchainKit",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-background dark">
        <Providers>
          <AmountProvider><XMTPProvider><BillNotificationListener />{children}</XMTPProvider></AmountProvider>
        </Providers>
      </body>
    </html>
  );
}
